import argparse


def get_args():
    parser = argparse.ArgumentParser()
    group = parser.add_argument_group(title="data config")
    group.add_argument("--dataset-name", type=str, required=True, help="name of the dataset")
    group.add_argument("--dataset-path", type=str, required=True, help="path of the dataset")
    group.add_argument(
        "--cls-num", type=int, default=None, help="number of categories in classification tasks"
    )
    group.add_argument("--output-path", type=str, default="output", help="path of output files")

    group = parser.add_argument_group(title="tune config")
    group.add_argument("--model-path", type=str, required=True, help="path of the checkpoint")
    group.add_argument("--config-path", type=str, required=True, help="path of the config file")
    group.add_argument("--batch-size", type=int, default=32, help="batch size in the training loop")
    group.add_argument(
        "--early-stop-patience",
        type=int,
        default=10,
        help="number of times the loss does not drop on validation set before we stop training",
    )
    group.add_argument(
        "--eval-interval", type=int, default=50, help="number of steps to conduct evaluation"
    )
    group.add_argument(
        "--tune-maxlen", type=int, default=256, help="maximum sequence length in the tuning"
    )
    group.add_argument("--lr", type=float, default=5e-3, help="initial learning rate")
    group.add_argument("--warmup-iters", type=int, default=50, help="number of warm-up steps")
    group.add_argument("--epochs", type=int, default=10, help="number of epochs")

    group = parser.add_argument_group(title="infer config")
    group.add_argument(
        "--infer-maxlen",
        type=int,
        default=100,
        help="maximum number of tokens generated by the model",
    )

    args = parser.parse_args()
    return args
