name: "type check"
on:
  pull_request:
    branches:
      - "**"
jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jakebailey/pyright-action@v1
        with:
          working-directory: cpm-live


